### ISSUE TITLE
return 404 on https://test.payu.in/api/v2/orders

### ISSUE THREAD

**Issue by Gauravshah** [PayU/openpayu_ruby#14]
tried this gem with indian payment gateway and it resulted in a 404

**Comment by agnagna** [comment]
Hi, sdk do not support PayU India payment gateways.
Regards

**Comment by nullgr4vity** [comment]
hi Gauravshah,

if you are looking for SDK or plugins for India region please take a look for PayU India repository - https://github.com/payu-india

all the best
